apiVersion: v1
description: the community-maintained descendant of the stable/airflow helm chart - focused on ease-of-use
name: airflow
version: 8.2.1
appVersion: 2.0.1
icon: https://airflow.apache.org/_images/pin_large.png
home: https://airflow.apache.org/
maintainers:
  - name: thesuperzapper
    url: https://github.com/thesuperzapper
  - name: gsemet
    url: https://github.com/gsemet
sources:
  - https://github.com/airflow-helm/charts/tree/main/charts/airflow
keywords:
  - airflow
  - dag
  - workflow
