apiVersion: v1
description: airflow is a platform to programmatically author, schedule, and monitor workflows
name: airflow
version: 7.15.0
appVersion: 1.10.12
icon: https://airflow.apache.org/_images/pin_large.png
home: https://airflow.apache.org/
maintainers:
  - name: gsemet
    url: https://github.com/gsemet
  - name: thesuperzapper
    url: https://github.com/thesuperzapper
sources:
  - https://github.com/airflow-helm/charts/tree/main/charts/airflow
keywords:
  - airflow
  - dag
  - workflow
