apiVersion: v2
description: the community Apache Airflow Helm Chart - used to deploy Apache Airflow on Kubernetes
name: airflow
version: 8.4.1
appVersion: 2.1.1
icon: https://airflow.apache.org/_images/pin_large.png
home: https://airflow.apache.org/
maintainers:
  - name: thesuperzapper
    url: https://github.com/thesuperzapper
  - name: gsemet
    url: https://github.com/gsemet
sources:
  - https://github.com/airflow-helm/charts/tree/main/charts/airflow
keywords:
  - airflow
  - dag
  - workflow
dependencies:
  - name: postgresql
    version: 8.6.4
    repository: https://charts.helm.sh/stable
    condition: postgresql.enabled
  - name: redis
    version: 10.5.7
    repository: https://charts.helm.sh/stable
    condition: redis.enabled
