name: "Sync README.md to gh-pages Branch"

on:
  push:
    branches:
      - main
    paths:
      - "README.md"

jobs:
  sync_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `main` Branch
        uses: actions/checkout@v3

      - name: Copy `README.md` to Runner
        run: |
          cp -f README.md ${{ runner.temp }}/README.md

      - name: Checkout `gh-pages` Branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Commit new `README.md` to `gh-pages` Branch
        run: |
          cp -f ${{ runner.temp }}/README.md .
          git add README.md
          git commit --signoff -m "chore: sync README.md from main branch"
          git push